### PR TITLE
Fixes ElTheLedge/ValheimMods#7

### PR DESCRIPTION
**Pull request by kadamczy**
changed method name to account for 0.216.9 changes

### CODE REVIEW

**Comment by ElTheLedge** [comment]
Thanks for the request but I tried that and sadly GetRightItem() and GetLeftItem() are now protected which means I can't call them like I did before, so that alone didn't fix it.
For now I have also disabled the abiltiy to use the config file while looking for a fix.
If you have a solution to that, feel free to make another pull request

**Comment by kadamczy** [comment]
I don't do a lot of modding, but I did see that I had to enable "allow unsafe execution of code" to allow it to use GetRightItem and GetLeftItem. It was working on my build at least! 

I wasn't sure if I should push the csproj file as well which would have included that bit.

FWIW this mod is a massive QoL improvement for me which is why I thought I'd just do a little bit to help!

**Comment by ElTheLedge** [comment]
You're right that does work, I didn't even think about trying that.
Though I don't know if that could have any potential side effects?
I really don't do a lot of C# so I don't know

**Comment by kadamczy** [comment]
The unsafe flag won't make a difference in the code you wrote.  Generally it's used when you're doing memory-level coding (like using pointers which c# generally manages for you). My guess is that as part of their optimizations used some "unsafe" code to help speed things up and the GetRightItem/GetLeftItem were impacted by them.

Either way I'm glad to see it updated! Cheers!

**Pull request closed without merging**
